# Site settings
title: INARGIA
description:
  en: Engineering Applied in Energy.
  es: Ingeniería Aplicada en Energía.
url: "https://www.inargiaco.com"

# User setting
email: info@inargiaco.com
linkedin: inargia

# Build settings
markdown: kramdown
